# Generated by Django 3.2.23 on 2023-12-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_currency',
            field=models.CharField(max_length=20),
        ),
    ]
