# Generated by Django 3.2.23 on 2023-12-14 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_country_country_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='countries.country'),
        ),
    ]
